services:
  db:
    image: postgres:latest
    command: postgres -p ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      - DJANGO_SUPERUSER_PASSWORD=veryhard
    command: bash -c "python manage.py migrate &&
                      python manage.py loaddata fixtures.json &&
                      python manage.py createsuperuser --noinput || true &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  pgdata:
