# Generated by Django 5.2.4 on 2025-07-16 12:59

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashFlowRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date of creation of the record (Optional, If is not specified, will be used today's date)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in rub.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("comment", models.TextField(blank=True, help_text="Optional Comment")),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category of the record (must match the category in subcategory)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="references.category",
                    ),
                ),
                (
                    "flow_type",
                    models.ForeignKey(
                        help_text="Type of the cash flow (must match the type in category)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="references.flowtype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Status of the record",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="references.status",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        help_text="Subcategory of the record",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="references.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Flow Record",
                "verbose_name_plural": "Cash Flow Records",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="records_cas_date_956c90_idx")
                ],
            },
        ),
    ]
